/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrames;

import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;
import org.beans.Paciente;


/**
 *
 * @author Armando
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Bienvenido");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPanel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtNombrePacienteCita = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescipcionCita = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        CheckConfirmada = new javax.swing.JCheckBox();
        CheckPendiente = new javax.swing.JCheckBox();
        CheckCancelada = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNombrePacienteReceta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFechaReceta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEnfermedadesReceta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTratamientosReceta = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtEmailPaciente = new javax.swing.JTextField();
        txtNombrePaciente1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbSexoPaciente = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreNuevoPaciente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPacienteEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccionNuevoPaciente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbListaPacientes1 = new javax.swing.JComboBox();
        btnNuevoPaciente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabPanel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Avant Guard", 0, 48)); // NOI18N
        jLabel3.setText("Centro Médico");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 70));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Cedula No. 1590876");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setText("Av. Siempre viva #178 B");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Avant Guard", 0, 48)); // NOI18N
        jLabel6.setText("Dr. Luis Perez");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, 70));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Médico General, Cirujano");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrames/doctor.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        TabPanel.addTab("Inicio", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 102, 150, 0));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 20, 310));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel20.setText("Descripción");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
        jPanel4.add(txtNombrePacienteCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 250, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel21.setText("Estado");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        txtAreaDescipcionCita.setColumns(20);
        txtAreaDescipcionCita.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAreaDescipcionCita.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescipcionCita);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 470, 220));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel22.setText("Nombre del Paciente");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        CheckConfirmada.setText("Confirmada");
        jPanel4.add(CheckConfirmada, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        CheckPendiente.setText("Pendiente");
        jPanel4.add(CheckPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        CheckCancelada.setText("Cancelada");
        jPanel4.add(CheckCancelada, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, -1, -1));

        TabPanel.addTab("Citas", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 5, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 5, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setText("Enfermedades:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));
        jPanel1.add(txtNombrePacienteReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel17.setText("Nombre del paciente");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(txtFechaReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 110, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setText("Fecha:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setText("Tratamientos:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtAreaEnfermedadesReceta.setColumns(20);
        txtAreaEnfermedadesReceta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAreaEnfermedadesReceta.setRows(5);
        jScrollPane1.setViewportView(txtAreaEnfermedadesReceta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 350, 210));

        txtAreaTratamientosReceta.setColumns(20);
        txtAreaTratamientosReceta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAreaTratamientosReceta.setRows(5);
        jScrollPane2.setViewportView(txtAreaTratamientosReceta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 350, 210));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 10, 310));

        jButton1.setText("Guardar ");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 80, 50));

        TabPanel.addTab("Receta", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Lista de Pacientes");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel3.add(txtEmailPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 250, -1));
        jPanel3.add(txtNombrePaciente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 250, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Nombre del Paciente");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 20, 320));

        cmbSexoPaciente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cmbSexoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel10.setText("Nuevo Paciente");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Email");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        txtNombreNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreNuevoPacienteActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombreNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 250, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Nombre del paciente");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel3.add(txtPacienteEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 250, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setText("E-Mail");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel3.add(txtDireccionNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 250, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Dirección");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Sexo");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        cmbListaPacientes1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cmbListaPacientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 240, -1));

        btnNuevoPaciente.setText("Agregar");
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 320, 110));

        TabPanel.addTab("Pacientes", jPanel3);

        getContentPane().add(TabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 880, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jFrames/s.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
      Paciente paci = new Paciente ();
       paci.setNombre_pa(txtNombreNuevoPaciente.getText());
       paci.se(txtPacienteEmail.getText());
       
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void txtNombreNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreNuevoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreNuevoPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckCancelada;
    private javax.swing.JCheckBox CheckConfirmada;
    private javax.swing.JCheckBox CheckPendiente;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JComboBox cmbListaPacientes1;
    private javax.swing.JComboBox cmbSexoPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtAreaDescipcionCita;
    private javax.swing.JTextArea txtAreaEnfermedadesReceta;
    private javax.swing.JTextArea txtAreaTratamientosReceta;
    private javax.swing.JTextField txtDireccionNuevoPaciente;
    private javax.swing.JTextField txtEmailPaciente;
    private javax.swing.JTextField txtFechaReceta;
    private javax.swing.JTextField txtNombreNuevoPaciente;
    private javax.swing.JTextField txtNombrePaciente1;
    private javax.swing.JTextField txtNombrePacienteCita;
    private javax.swing.JTextField txtNombrePacienteReceta;
    private javax.swing.JTextField txtPacienteEmail;
    // End of variables declaration//GEN-END:variables
}
